version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- pwsh: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a TrackStudio-Latest.zip "%APPVEYOR_BUILD_FOLDER%\Track Studio\bin\Release\net5.0\"


    appveyor PushArtifact "TrackStudio-Latest.zip"
artifacts:
- path: TrackStudio-Latest.zip
  name: TrackStudio
deploy:
- provider: GitHub
  release: Release
  repository: MapStudioProject/CTR-Studio
  artifact: TrackStudio